export type Gift = {
  id: string;
  name: string;
  category: string;
  price: string;
  image: string;
  gallery: string[];
  reason: string;
  meaning: string;
  description: string;
  story: string;
  delivery: string;
};

export const gifts: Gift[] = [
  { id: "pearl-strand", name: "The Pearl Strand", category: "A quiet classic", price: "$280", image: "https://images.unsplash.com/photo-1515562141207-7a88fb7ce338?auto=format&fit=crop&w=900&q=85", gallery: ["https://images.unsplash.com/photo-1515562141207-7a88fb7ce338?auto=format&fit=crop&w=1200&q=85", "https://images.unsplash.com/photo-1611652022419-a9419f74343d?auto=format&fit=crop&w=1200&q=85", "https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?auto=format&fit=crop&w=1200&q=85"], reason: "A luminous piece with enough restraint for every day, chosen for someone whose presence already says a lot.", meaning: "A reminder that the most enduring things do not need to ask for attention.", description: "A hand-finished strand of freshwater pearls with a softly irregular shape. Designed to become part of their everyday ritual, not wait for a special occasion.", story: "Each pearl carries a quiet variation: a small reminder that beauty is found in the details that cannot be repeated.", delivery: "Arrives gift-wrapped in 3–5 business days" },
  { id: "santal-candle", name: "Santal 33 Candle", category: "For their ritual", price: "$95", image: "https://images.unsplash.com/photo-1603006905003-be475563bc59?auto=format&fit=crop&w=900&q=85", gallery: ["https://images.unsplash.com/photo-1603006905003-be475563bc59?auto=format&fit=crop&w=1200&q=85", "https://images.unsplash.com/photo-1603006905003-be475563bc59?auto=format&fit=crop&w=1200&q=85", "https://images.unsplash.com/photo-1603006905003-be475563bc59?auto=format&fit=crop&w=1200&q=85"], reason: "A warm, tactile ritual for the person who finds beauty in slow mornings and the details of home.", meaning: "A little permission to pause, exhale, and make an ordinary evening feel intentional.", description: "A sculptural soy wax candle with notes of sandalwood, amber, and soft smoke. Made to turn a familiar room into somewhere worth lingering.", story: "Inspired by the hush of a late afternoon, this is a gift for the spaces between plans: the moments where life feels most like itself.", delivery: "Arrives in a signature box in 2–4 business days" },
  { id: "linen-journal", name: "The Linen Journal", category: "For their ideas", price: "$68", image: "https://images.unsplash.com/photo-1544816155-12df9643f363?auto=format&fit=crop&w=900&q=85", gallery: ["https://images.unsplash.com/photo-1544816155-12df9643f363?auto=format&fit=crop&w=1200&q=85", "https://images.unsplash.com/photo-1517842645767-c639042777db?auto=format&fit=crop&w=1200&q=85", "https://images.unsplash.com/photo-1517842645767-c639042777db?auto=format&fit=crop&w=1200&q=85"], reason: "Thoughtfully made space for the ideas, lists, sketches, and small observations that make their world distinct.", meaning: "A place for what they have not said yet, and for the future they are quietly making.", description: "Bound in natural linen with thick, uncoated pages that welcome ink, pencil, and the occasional beautiful accident.", story: "The first page is intentionally blank. It belongs entirely to them, waiting for a thought only they would have.", delivery: "Arrives wrapped with a handwritten card in 2–3 business days" },
  { id: "travel-case", name: "The Weekender Case", category: "For the curious", price: "$320", image: "https://images.unsplash.com/photo-1553062407-98eeb64c6a62?auto=format&fit=crop&w=900&q=85", gallery: ["https://images.unsplash.com/photo-1553062407-98eeb64c6a62?auto=format&fit=crop&w=1200&q=85", "https://images.unsplash.com/photo-1548036328-c9fa89d128fa?auto=format&fit=crop&w=1200&q=85", "https://images.unsplash.com/photo-1553531384-cc64ac80f931?auto=format&fit=crop&w=1200&q=85"], reason: "A beautifully considered companion for someone always carrying a story toward somewhere new.", meaning: "An invitation to keep choosing the next chapter, wherever it leads.", description: "A supple leather weekender with a generous interior, brass hardware, and a silhouette that gets better with every departure.", story: "Made for the last-minute escape and the trip planned months ahead. The best journeys rarely begin with an empty bag.", delivery: "Arrives in a reusable dust bag in 5–7 business days" },
];
